version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: "clojure:lein-2.7.1"
    steps:
      - checkout
      - restore_cache:
          key: build-{{ checksum "project.clj" }}
      - run:
          lein deps
      - save_cache:
          key:  build-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - run:
          lein do test2junit
      - store_test_results:
          path: /build/target/test2junit/xml
          destination: junit/build
  docker_image:
    working_directory: /build
    docker:
      - image: "deepimpact/jessie-lein-awscli-docker:1.0.1"
    steps:
      - checkout
      - restore_cache:
          key: build-{{ checksum "project.clj" }}
      - run:
          lein uberjar
      - save_cache:
          key:  build-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - setup_remote_docker:
          reusable: true
      - deploy:
          name: build image
          command: |
            ./circleci/build/build.sh
            ./circleci/build/push.sh
  deploy:
    working_directory: /build
    docker:
      - image: "clojure:lein-2.7.1"
    steps:
      - checkout
      - restore_cache:
          key: build-{{ checksum "project.clj" }}
      - deploy:
          command: ./circleci/deploy/deploy.sh
      - save_cache:
          key:  build-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

workflows:
  version: 2

  build_docker_deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /release.*/

    - docker_image:
        requires:
          - build
        filters:
          tags:
            only: /release.*/
          branches:
            ignore: /.*/

    - hold:
        type: approval
        requires:
          - docker_image
        filters:
          tags:
            only: /release.*/
          branches:
            ignore: /.*/

    - deploy:
        requires:
          - hold
        filters:
          tags:
            only: /release.*/
          branches:
            ignore: /.*/
